#!/usr/bin/env sh

echo "invoked when test is ok"

code=$1
output=$(echo "${2//!#\$@%}")
message=$(git log -1 --pretty=%B)
branch=$(git symbolic-ref --short HEAD)

payload=$(echo "{\"channel\":\"#continous2\",\"text\":\"Ran tests on *$branch*\n\`\`\`$message\`\`\`\n\`\`\`$output\`\`\`\n*TEST PASSED*\"}")

echo $payload

curl -X POST -H 'Content-type: application/json' \
     --data "$payload" https://hooks.slack.com/services/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
