#!/usr/bin/env sh

echo "invoked when test fails"

code=$(echo $1 | sed -e 's/\^\[\[[0-9;]\{2,\}m//g')
output=$(echo $2 | sed -e 's/\^\[\[[0-9;]\{2,\}m//g')
message=$(git log -1 --pretty=%B )
branch=$(git symbolic-ref --short HEAD)

payload=$(echo "{\"channel\":\"#ci\",\"text\":\"Ran tests on *$branch*\n\n\`\`\`$message\`\`\`\`\`\`$output\`\`\`*TEST PASSED*\"}")

curl -X POST -H 'Content-type: application/json' \
     --data "$payload" https://hooks.slack.com/services/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