-- MySQL Workbench Synchronization

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `entree_r1`.`Orders`
ADD COLUMN `transactionId` VARCHAR(36) NULL DEFAULT NULL AFTER `message`,
ADD UNIQUE INDEX `transactionId` (`transactionId` ASC);

ALTER TABLE `entree_r1`.`Sizes`
CHANGE COLUMN `name` `name` VARCHAR(12) NOT NULL ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
