-- MySQL Workbench Synchronization

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `entree_r14`.`restaurants` 
CHANGE COLUMN `name` `name` VARCHAR(64) NOT NULL ,
CHANGE COLUMN `handle` `handle` VARCHAR(25) NOT NULL ,
CHANGE COLUMN `password` `password` VARCHAR(64) NOT NULL ,
CHANGE COLUMN `phoneNumber` `phoneNumber` VARCHAR(10) NULL DEFAULT NULL ,
CHANGE COLUMN `profileImage` `profileImage` VARCHAR(512) NULL DEFAULT NULL ,
CHANGE COLUMN `mode` `mode` ENUM('REGULAR','GOD','UNAVAILABLE') NOT NULL ,
CHANGE COLUMN `merchantId` `merchantId` VARCHAR(32) NULL DEFAULT NULL ;

ALTER TABLE `entree_r14`.`users` 
ADD COLUMN `receiptCount` INT(11) NOT NULL DEFAULT '1' AFTER `fbId`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
