-- MySQL Workbench Synchronization

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `entree_r2`.`ChatStates` 
ADD COLUMN `OrderId` INT(11) NULL DEFAULT NULL AFTER `MenuItemId`,
ADD COLUMN `ItemModId` INT(11) NULL DEFAULT NULL AFTER `OrderId`,
ADD INDEX `OrderId` (`OrderId` ASC),
ADD INDEX `ItemModId` (`ItemModId` ASC);

ALTER TABLE `entree_r2`.`ItemMods` 
DROP COLUMN `addPrice`,
ADD COLUMN `min` INT(11) NOT NULL AFTER `name`,
ADD COLUMN `max` INT(11) NOT NULL AFTER `min`;

CREATE TABLE IF NOT EXISTS `entree_r2`.`Mods` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NOT NULL,
  `addPrice` INT(11) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `ItemModId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ItemModId` (`ItemModId` ASC),
  CONSTRAINT `mods_ibfk_1`
    FOREIGN KEY (`ItemModId`)
    REFERENCES `entree_r2`.`ItemMods` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ALTER TABLE `entree_r2`.`ChatStates` 
ADD CONSTRAINT `chatstates_ibfk_4`
  FOREIGN KEY (`OrderId`)
  REFERENCES `entree_r2`.`Orders` (`id`)
  ON DELETE SET NULL
  ON UPDATE CASCADE,
ADD CONSTRAINT `chatstates_ibfk_5`
  FOREIGN KEY (`ItemModId`)
  REFERENCES `entree_r2`.`ItemMods` (`id`)
  ON DELETE SET NULL
  ON UPDATE CASCADE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
