-- MySQL Workbench Synchronization

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER SCHEMA `entree_r3`  DEFAULT CHARACTER SET utf8  DEFAULT COLLATE utf8_general_ci ;

ALTER TABLE `entree_r3`.`Mods` 
DROP FOREIGN KEY `Mods_ibfk_1`;

ALTER TABLE `entree_r3`.`ItemMods` 
CHANGE COLUMN `name` `name` VARCHAR(32) NOT NULL ;

ALTER TABLE `entree_r3`.`MenuItems` 
CHANGE COLUMN `name` `name` VARCHAR(32) NOT NULL ;

ALTER TABLE `entree_r3`.`Mods` 
CHARACTER SET = utf8 , COLLATE = utf8_general_ci ,
CHANGE COLUMN `name` `name` VARCHAR(64) NOT NULL ;

ALTER TABLE `entree_r3`.`OrderItems` 
CHANGE COLUMN `name` `name` VARCHAR(128) NOT NULL ;

ALTER TABLE `entree_r3`.`Sizes` 
CHANGE COLUMN `name` `name` VARCHAR(16) NOT NULL ;

ALTER TABLE `entree_r3`.`Mods` 
ADD CONSTRAINT `mods_ibfk_1`
  FOREIGN KEY (`ItemModId`)
  REFERENCES `entree_r3`.`ItemMods` (`id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
