#!/usr/bin/env sh

grunt cordova-prepare --force || true

username=$(curl -L ${SSH_OSX_USERNAME})
hostname=$(curl -L ${SSH_OSX_HOSTNAME})
port=$(curl -L ${SSH_OSX_PORT})
password=$(curl -L ${SSH_OSX_PASSWORD})
dir=$RANDOM
message=$(git log -1 --pretty=%B)
branch=${BRANCHOFF_BRANCH}
version=$(echo $(npm version) | egrep -o "'(.*?)'" | sed -n 2p | sed 's/^.\(.*\).$/\1/')

rm -rf ../cordova/build/ || true
rm -rf ../public/Entree.apk || true
rm -rf ../public/Entree.ipa || true
mkdir -p ../cordova/build/
zip -r ${dir}.zip ../cordova # TODO fix relative path issue
sshpass -p ${password} scp -o StrictHostKeyChecking=no -P ${port} ${dir}.zip ${username}@${hostname}:~/Github/builds/
sshpass -p ${password} ssh -o StrictHostKeyChecking=no -p ${port} ${username}@${hostname} "
        unzip -oq ~/Github/builds/${dir}.zip -d ~/Github/builds/${dir}"
sshpass -p ${password} ssh -o StrictHostKeyChecking=no -p ${port} ${username}@${hostname} "
        bash -c \"source ~/.bash_profile
        security unlock-keychain -p ${password} ~/Library/Keychains/login.keychain
        cd ~/Github/builds/${dir}/cordova
        cordova prepare
        cordova prepare ios
        cordova prepare android
        cordova build android --release --buildConfig=build.json
        cordova build ios --device\""
sshpass -p ${password} scp -o StrictHostKeyChecking=no -P ${port} ${username}@${hostname}:~/Github/builds/${dir}/cordova/platforms/android/build/outputs/apk/android-release.apk ../cordova/build/Entree.apk
sshpass -p ${password} scp -o StrictHostKeyChecking=no -P ${port} ${username}@${hostname}:~/Github/builds/${dir}/cordova/platforms/ios/build/device/Entree.ipa ../cordova/build/Entree.ipa
rm ${dir}.zip

# # clean up remote: enable once this process is ready
sshpass -p ${password} ssh -o StrictHostKeyChecking=no  -p ${port} ${username}@${hostname} "rm ~/Github/builds/${dir}.zip"
sshpass -p ${password} ssh -o StrictHostKeyChecking=no  -p ${port} ${username}@${hostname} "rm -rf ~/Github/builds/${dir}"

# push ios release
ios_raw=$(curl https://api.tryouts.io/v1/applications/NCKHE4E1/releases/ \
    -F "build=@../cordova/build/Entree.ipa" \
    -F "notes=$message" \
    -F "version=$version" \
    -F "notify=1" \
    -F "status=2" \
    -H "Authorization: b0fbf0eb2c9fded09aefdcf2eeff759c:73da365b26d0ff39f865f285012538fa69d8405e")

# push android release
android_raw=$(curl https://api.tryouts.io/v1/applications/6A6cacUG/releases/ \
    -F "build=@../cordova/build/Entree.apk" \
    -F "notes=$message" \
    -F "version=$version" \
    -F "notify=1" \
    -F "status=2" \
    -H "Authorization: b0fbf0eb2c9fded09aefdcf2eeff759c:73da365b26d0ff39f865f285012538fa69d8405e")

ios_url=$(echo ${ios_raw} | sed 's/.*"download_url": "\(.*\)", "size".*/\1/p')
android_url=$(echo ${android_raw} | sed 's/.*"download_url": "\(.*\)", "size".*/\1/p')

payload=$(echo "{\"channel\":\"#continous3\",\"text\":\"*$branch*\n\`\`\`$message\`\`\`\n*iOS*\n$ios_url\n*Android*\n$android_url\"}")

curl -X POST -H 'Content-type: application/json' --data "$payload" https://hooks.slack.com/services/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
