#!/usr/bin/env sh

message=$(git log -1 --pretty=%B)

if [[ ${message} == *"--skip-tests"* ]]
then
    exit
fi

if [[ $1 != *"local-stage"* ]]; then
    sleep 10
fi

export IS_RUNNING_TEST=true;

set -e
npm run tests-ci
npm run lint-ci